D2P = {
    "Uriah Hawthorne": "Abyssal Melodies",
    "Anneliese Worley": "The Theft of the Starry Night",
    "Tyler Oakridge": "Ares Mission",
    "Sierra Pemberton": "The Essence of Humanity",
    "Theodore Sterling": "Mariana Trench",
    "Aurora Chamberlain": "SunBird",
    "Leona Hargrove": "Cure for the Common Cold",
    "Graham Redwood": "The Celestial Lift",
    "Felix Dunford": "Atlantis",
    "Zachary Norwood": "Great Earthquake of 2065",
    "Cassidy Worthington": "Android Orchestra",
    "William Blackwell": "Dreamcatcher",
    "Delilah Norwood": "Unicorns",
    "Nola Westbrook": "Celestial Odyssey",
    "Nathaniel Crestwood": "EverBloom",
    "Quentin Brookfield": "Zero-Gravity Ballet",
    "Tessa Montgomery": "Hoverbike Racing",
    "Carter Graystone": "Subterranean World",
    "Xavier Pendleton": "Solo Submarine Voyage",
    "Cassidy Hammond": "New Atlantis",
    "Julian Wakefield": "Sahara Desert Hoverbike Trek",
    "Harrison Ashford": "ZeroGravity Boots",
    "Bridget Marston": "Global Fusion Bistro",
    "Mariana Underwood": "Shadow Government Expose",
    "Katrina Shelton": "Quadruple Backflip Hoverboard",
    "Samuel Rockford": "Virtual Reality Olympics",
    "Preston Windgate": "Global Social Equality",
    "Oliver Stonebridge": "Amazon River Swim",
    "Xavier Fairmont": "Reversing Aging",
    "Lucas Rainford": "Hope Worldwide"
}

P2D = {
    "Daphne Barrington": "A Journey Through Time",
    "Owen Larkspur": "Extraterrestrial Contact",
    "Dominic Mullins": "Kraken",
    "Juliette Radcliffe": "Moonlight Couture",
    "Keith Silverton": "Lunar Wine",
    "Garrett Bridgewell": "World Hoverboard Championships",
    "Derek Lindenwood": "Lemuria",
    "Ryan Dunsworth": "Teleportation Device",
    "Nolan Evergreen": "Dark Matter",
    "Sabrina Fairchild": "Symphony of the Stars",
    "Alana Everhart": "Highest-altitude Skydive",
    "Liam Blackstone": "Nebula Cocktail",
    "Mallory Blackwood": "Meal in Outer Space",
    "Giselle Whitmore": "Voynich Manuscript",
    "Ethan Westfield": "Oasis Tower",
    "Maia Carlisle": "Arctic Map",
    "Fallon Huxley": "Global Reforestation Project",
    "Connor Gravestone": "Lunar Haven",
    "Evan Lockhart": "City of Zanaris",
    "Ariana Lockwood": "StarPath",
    "Leilani Prescott": "Rainbow Mermaid",
    "Alicia Stratford": "Great Inferno of 2041",
    "Selena Granger": "MindLink",
    "Andrew Sandbourne": "Cyberspace Defense Force",
    "Celeste Whitaker": "Eiffel Tower Disappearance",
    "Rosalind Baxter": "Escape from the Black Hole",
    "Veda Langston": "Skyward Gardens",
    "Cora Bellingham": "Great Storm of 2059",
    "Rowena Caldwell": "Drone Racing",
    "Alexander Whitley": "Ice Skating on Europa"
}

BOTH_DIR = {
    "Mason Caldwell": "Emotional AI",
    "Evangeline Huntley": "Stone Forest",
    "Elise Caldwell": "Loch Ness Monster",
    "Valerie Archer": "Poseidon's Cove",
    "Victor Whitestone": "Infinity Chandelier",
    "Kira Beaumont": "Desert Symphony",
    "Sariya Breckenridge": "The Quantum Detective",
    "Lacey Donnelly": "Unleashing Your Inner Superhero",
    "Yannick Rosemont": "Enchanted Strings",
    "Isaac Goldsmith": "Aqua Utopia",
    "Ivan Kingsley": "SunWear",
    "Danae Millington": "Intergalactic Peace Award",
    "Brian Thornhill": "Vertical Farming Skyscraper",
    "Tabitha Beauregard": "Treasure of the Dragon's Den",
    "Avery Copperfield": "Mars Rover Racing",
    "Gemma Northwood": "Frozen Dreams",
    "Annika Hammersmith": "Golden City of El Dorado",
    "Holden Fairview": "Education for All",
    "Vincent Eastwood": "Earth's magnetic field",
    "Frederick Ironwood": "Antimatter Energy",
    "Maxwell Alderwood": "Hidden Realm of Atlantis",
    "Meredith Keating": "Forever Young Gene",
    "Isla Braxton": "Zero-Gravity Cooking",
    "Zachariah Blackthorn": "Quantum Chess World Championship",
    "Wesley Braxton": "Vanishing Village",
    "Penelope Landon": "Underwater Train System",
    "Fiona Gallagher": "Solar-Powered Glider",
    "Bianca Stanfield": "Europa Colony",
    "Kyle Northwood": "Holographic Entertainment",
    "Eliza Thorne": "ChocoCloud Souffle"
}

COMPANIES = [
    "QuantumLeap Innovations",
    "AeroZenith Technologies",
    "StellarWave Solutions",
    "TerraVista Corp",
    "NexaFusion Enterprises",
    "ApexCrest Industries",
    "VortexPrime Systems",
    "ZenithSphere Networks",
    "AuroraNova Labs",
    "HelixPulse Dynamics",
    "TitanEdge Solutions",
    "OrbitFlow Enterprises",
    "FusionPeak Technologies",
    "VectorGlow Industries",
    "HyperNexus Innovations",
    "SpectraWave Dynamics",
    "HorizonPulse Corp",
    "AstroFusion Solutions",
    "QuantumVista Labs",
    "InnovateLyft Technologies",
    "TerraGlow Systems",
    "ApexFusion Enterprises",
    "VectorNova Industries",
    "StellarPulse Labs",
    "TitanNexus Dynamics",
    "OrbitZenith Solutions",
    "HelixWave Enterprises",
    "HyperEdge Technologies",
    "SpectraNexus Innovations",
    "AuroraLyft Dynamics"
]
